server:
  port: 8585

spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 50
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    name: dataflow_queue
  exchange:
    name: dataflow_exchange
  routing:
    key: dataflow_routing_key